### PR TITLE
Fix es2015 compilation error

### PR DESCRIPTION
**Pull request by Sebubu**
Hi @mclaeysb 

Great small library you have built here! 

We are using your simplepolygon library to split up self intersecting polygons on our front end. Unfortunately as we are moving to [ES2015](https://babeljs.io/docs/en/learn/), geojson-polygon-self-intersections is not able to run anymore without errors.
As it is a simple fix, I hope you can merge it and update `geojson-polygon-self-intersections` and `simplepolygon` on npm.

Just tell me if you are too busy. I will then just fork the projects and create two new npm projects with the updated code.

Best regards

Severin

### CODE REVIEW

**Comment by mclaeysb** [comment]
Glad to hear this library is useful. I'll take a look at this next week!

**Comment by Sebubu** [comment]
Hey @mclaeysb 
Thanks for merging the pull request. Do you intent to update `geojson-polygon-self-intersections` and `simplepolygon` on npm?

Best regards
Sevi

**Comment by mclaeysb** [comment]
Forgot :)

Should be done now!

Curious what you are using it for. Could you tell me something about it?

Kind regards
Manuel

Op wo 9 okt. 2019 om 08:54 schreef Severin Bühler <notifications@github.com

**Comment by Sebubu** [comment]
> Forgot :) Should be done now! Curious what you are using it for. Could you tell me something about it? Kind regards Manuel

Thanks!

We are using it in combination with [OpenLayers](https://github.com/openlayers/openlayers). In OpenLayers, the user is able to draw self intersecting polygons. Like you surely know, self intersecting polygons are a nasty thing. 
Your library resolves them immediately and makes the drawing polygon experience way more pleasant.

Cheers

**Comment by mclaeysb** [comment]
Cool! What is the application you are building? Can I access it myself?

Op wo 9 okt. 2019 om 12:04 schreef Severin Bühler <notifications@github.com

**Comment by Sebubu** [comment]
We have build a geojson editor like geojson.io. It is only used in our Intranet, so I can't show you anything.

**Pull request merged**
